### ISSUE TITLE
Add "JAVA Home" (Intelij) information to README

### ISSUE THREAD

**Issue by joethe** [UMM-CSci-3601/3601-lab2_client-server#17]
This is a non-obvious part of starting to use Intelij for the first time, so we should add some notes about how to actually do this.

**Comment by kklamberty** [comment]
I'm going to write the notes about what to do here. We didn't get this done by the milestone, so this should be verified and added in the right place more carefully. But, since it wasn't even obvious to us, I want to get these notes written up now.

From the welcome screen of IntelliJ, in the lower right corner-ish area, click on Configure.
Choose "Project Defaults"
Choose "Project Structure"
In the Project SDK section, there is a dropdown menu for the SDK to select. If there is no SDK, it will say so in red "<No SDK>". There is a button to the right of that that says "New...". Click that button. In our lab, you can find Java in /usr/lib/jvm/java

**Comment by NicMcPhee** [comment]
The notes above are specific to the welcome; we should add notes for people who aren't there. Probably just close the old project they have open and then they'll be at the welcome screen and can continue.

**Comment by NicMcPhee** [comment]
I feel like this may be a non-issue now, but I'm not 100% sure. @kklamberty – do you think this still comes up?
