### ISSUE TITLE
Make the server setup closer to the production template

### ISSUE THREAD

**Issue by kklamberty** [UMM-CSci-3601/3601-lab2_client-server#78]
There are several aspects of the current server setup that are different enough from the future work in the course to make it confusing when students finally get to deploy on droplets. We may be able to do some work toward making the setup here match the future in some ways.

**Comment by floogulinc** [comment]
Some of these won't be able to be changed in this lab but will in the next one, namely the client files being served by the Java server since there are no client build tools or dev server for this lab.

**Comment by NicMcPhee** [comment]
@kklamberty Coming back to this a year later, and I don't really know what you were thinking of here.

The file structure is more-or-less the same. The biggest difference is that the server build info is out on the top level instead of inside `server` like it is later. I think, as @floogulinc points out, that is kind of unavoidable here, but will be fixed in the next lab when there are build tools for both the serve and the client.

**Comment by kklamberty** [comment]
@NicMcPhee I think it's possible that the comment was made in a context where it made sense at that time, but changes made to later parts have meant it's not as big of a problem here? Frankly... wasn't this before we had Javalin? I had taught the course in the fall without Javalin and then we moved to Javalin in the spring and made a bunch of changes... maybe?

**Comment by NicMcPhee** [comment]
No, this was one year ago, so the semester we first used Javalin. _But_ you might have made the comment before we actually made (or complete) that switch?

Should we just close this?
